export const kardex = [
    {
        id: 1,
        time: "2023-12-12",
        product: "Paracetamol",
        tipoTransacction: "entrada",
        count: 10,
        description: "Compra inicial",
        userId: 1,
        expirationDate: "2023-12-31",
        supplierId: 2,
    },
    {
        id: 2,
        time: "2023-11-15",
        product: "Ibuprofeno",
        tipoTransacction: "entrada",
        count: 20,
        description: "Compra mensual",
        userId: 2,
        expirationDate: "2024-11-15",
        supplierId: 3,
    },
    {
        id: 3,
        time: "2023-10-10",
        product: "Amoxicilina",
        tipoTransacction: "entrada",
        count: 15,
        description: "Compra trimestral",
        userId: 3,
        expirationDate: "2024-10-10",
        supplierId: 4,
    },
    {
        id: 4,
        time: "2023-09-05",
        product: "Clorfenamina",
        tipoTransacction: "entrada",
        count: 25,
        description: "Compra semestral",
        userId: 4,
        expirationDate: "2024-09-05",
        supplierId: 5,
    },
    {
        id: 5,
        time: "2023-08-20",
        product: "Diclofenaco",
        tipoTransacction: "entrada",
        count: 30,
        description: "Compra anual",
        userId: 5,
        expirationDate: "2024-08-20",
        supplierId: 6,
    },
    {
        id: 6,
        time: "2023-07-15",
        product: "Metformina",
        tipoTransacction: "entrada",
        count: 40,
        description: "Compra mensual",
        userId: 6,
        expirationDate: "2024-07-15",
        supplierId: 7,
    },
    {
        id: 7,
        time: "2023-06-10",
        product: "Loratadina",
        tipoTransacction: "entrada",
        count: 50,
        description: "Compra trimestral",
        userId: 7,
        expirationDate: "2024-06-10",
        supplierId: 8,
    },
    {
        id: 8,
        time: "2023-05-05",
        product: "Omeprazol",
        tipoTransacction: "entrada",
        count: 60,
        description: "Compra semestral",
        userId: 8,
        expirationDate: "2024-05-05",
        supplierId: 9,
    },
    {
        id: 9,
        time: "2023-04-01",
        product: "Azitromicina",
        tipoTransacction: "entrada",
        count: 70,
        description: "Compra anual",
        userId: 9,
        expirationDate: "2024-04-01",
        supplierId: 10,
    },
    {
        id: 10,
        time: "2023-03",
        product: "Prednisona",
        tipoTransacction: "entrada",
        count: 80,
        description: "Compra mensual",
        userId: 10,
        expirationDate: "2024-03-25",
        supplierId: 11,
    }
];
